force add

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,6 +36,8 @@ jobs:
         cd openaip-openair-parser
         npm install
         echo "## Validating ..."
+        echo "#############DEBUG"
+        ls
         SCRIPT_OUTPUT=$(node ./cli.js -f ../france.txt -V -o ../france.geojson)
         SCRIPT_RC=$?
         echo "::set-output name=parser-output::$SCRIPT_OUTPUT"
@@ -52,18 +54,18 @@ jobs:
 
         git add ./france.geojson
         
-        set +e  # Grep succeeds with nonzero exit codes to show results.
-        git status | grep modified
-        if [ $? -eq 0 ]
-        then
-            set -e
-            git commit -m "Auto generated file"
-            git pull
-            git push
-        else
-            set -e
-            echo "No changes since last run"
-        fi
+#        set +e  # Grep succeeds with nonzero exit codes to show results.
+#        git status | grep modified
+#        if [ $? -eq 0 ]
+#        then
+        set -e
+        git commit -m "Auto generated file"
+        git pull
+        git push
+#        else
+#            set -e
+#            echo "No changes since last run"
+#        fi
 
   web-deploy:
     name: 🎉 Upload files to FTP
