Push geojson to repo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ on:
   workflow_dispatch:
     inputs:
       pushToFTP:
-          description: 'True if the action is triggered manually'
+          description: 'pushToFTP=true if the action is triggered manually'
           required: true
           default: true
 
@@ -39,6 +39,28 @@ jobs:
         SCRIPT_OUTPUT=$(node ./cli.js -f ../france.txt -V -o ../france.geojson)
         SCRIPT_RC=$?
         echo "::set-output name=parser-output::$SCRIPT_OUTPUT"
+
+    - name: ⚙️ Push .geojson to repo
+      run: |
+        # push to repo
+        echo "Pushing .geojson to repo"
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+        git add france.geojson
+        
+        set +e  # Grep succeeds with nonzero exit codes to show results.
+        git status | grep modified
+        if [ $? -eq 0 ]
+        then
+            set -e
+            git commit -m "Auto generated file"
+            git pull
+            git push
+        else
+            set -e
+            echo "No changes since last run"
+        fi
 
   web-deploy:
     name: 🎉 Upload files to FTP
